table scrbwa_gliederung
	lineageTag: 8e62422e-150f-4bd1-854d-3b2bfce2690b

	column sachkonto
		dataType: int64
		formatString: 0
		lineageTag: ee2420e8-934b-4012-a7b8-475861d0936a
		summarizeBy: none
		sourceColumn: sachkonto

		annotation SummarizationSetBy = Automatic

	column berichtsebene1
		dataType: string
		lineageTag: ab47ae98-db6b-4959-9722-9e47466e0064
		summarizeBy: none
		sourceColumn: berichtsebene1

		annotation SummarizationSetBy = Automatic

	column berichtsebene2
		dataType: string
		lineageTag: b1bcb195-cee3-41d4-8210-884a2ed3d160
		summarizeBy: none
		sourceColumn: berichtsebene2

		annotation SummarizationSetBy = Automatic

	column berichtsebene3
		dataType: string
		lineageTag: cfc024c1-7661-417c-9e11-1586ef05603e
		summarizeBy: none
		sourceColumn: berichtsebene3

		annotation SummarizationSetBy = Automatic

	partition scrbwa_gliederung = m
		mode: import
		queryGroup: DimTable
		source =
				let
				    Source = Sql.Database("ossak5xipqoubkgqopiawwyvhe-jhr7mosaqa5urewk2yeus4croa.datawarehouse.fabric.microsoft.com", "BWA_Ice_hockey_LH"),
				    dbo_scrbwa_gliederung = Source{[Schema="dbo",Item="scrbwa_gliederung"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(dbo_scrbwa_gliederung),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"sachkonto", Int64.Type}, {"berichtsebene1", type text}, {"berichtsebene2", type text}, {"berichtsebene3", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

